<a href="https://colab.research.google.com/github/Abhishekksoni/deep_learning/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor([[1, 2],
                       [4, 5]])
x.ndim

2

In [ ]:
tensor_t = tensor.T
tensor_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
tensor_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
x.permute(tuple(torch.arange(x.ndim-1, -1, -1)))

tensor([[1, 4],
        [2, 5]])

In [ ]:
x.mT


tensor([[1, 4],
        [2, 5]])

In [ ]:
y = torch.chunk(x,2, 0)
y

(tensor([[1, 2]]), tensor([[4, 5]]))

In [ ]:
torch.cuda.random.manual_seed(1234)
random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

(tensor([[0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
         [0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883],
         [0.0500, 0.4663, 0.9397, 0.2961, 0.9515, 0.6811, 0.0488],
         [0.8163, 0.4423, 0.2768, 0.8998, 0.0960, 0.5537, 0.3953],
         [0.8571, 0.6396, 0.7403, 0.6766, 0.3798, 0.3948, 0.0880],
         [0.7709, 0.8970, 0.8421, 0.1473, 0.5223, 0.1475, 0.2248],
         [0.2086, 0.6709, 0.2020, 0.4891, 0.5210, 0.8223, 0.1220]]),
 torch.Size([7, 7]))

In [ ]:
one_seven_tensor = torch.rand(1,7)
one_seven_tensor

tensor([[0.1567, 0.2097, 0.8500, 0.3203, 0.9217, 0.6808, 0.5633]])

In [ ]:
transpose_matrix = one_seven_tensor.mT
transpose_matrix

tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])

In [ ]:
martix_mul = random_tensor @ transpose_matrix
martix_mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.manual_seed(1234)
one_random = torch.rand(2,3)
two_random = torch.rand(2,3)

one_random, two_random, one_random.device, two_random.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]),
 device(type='cpu'),
 device(type='cpu'))

In [ ]:
one_random.to(device = 'cuda')

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [ ]:
two_random.to(device = 'cuda')

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')

In [ ]:
transpose_martix = two_random.mT

matrix_mul = one_random @ transpose_martix
matrix_mul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [ ]:
max = torch.max(matrix_mul)
min = torch.min(matrix_mul)
max, min

(tensor(0.5617), tensor(0.3647))

In [ ]:
max_index = torch.argmax(matrix_mul)
min_index = torch.argmin(matrix_mul)
max_index, min_index

(tensor(3), tensor(0))

In [ ]:
torch.manual_seed(7)
ran_tensor = torch.rand(1,1,1,10)
ran_tensor


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [ ]:
ran_tensor.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [ ]:
import torch
dif_tensor = torch.tensor([[1,2, 3,4],
                           [3,4,5,6],
                           [5,6,7,8]])
dif_tensor

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 7, 8]])

In [ ]:
""